### ISSUE TITLE
module 't_ragx' has no attribute 'processors'

### ISSUE THREAD

**Issue by AsherYangg** [rayliuca/T-Ragx#16]
Hi,
When i try to run the code in colab, it shows :  module 't_ragx' has no attribute 'processors'.

Code:
input_processor = t_ragx.processors.ElasticInputProcessor()

input_processor.load_general_glossary()
input_processor.load_general_translation(elastic_index="general_translation_memory", elasticsearch_host=["https://t-ragx-fossil.rayliu.ca", "https://t-ragx-fossil2.rayliu.ca"])
![Screenshot 2024-10-11 142659](https://github.com/user-attachments/assets/e117f55c-6688-4dac-9345-d8f8f6b43d4a)

**Comment by rayliuca** [comment]
Hi @AsherYangg, it looks like the `llama-cpp-python` installation failed, which left the environment in a bad state

I have pinned `llama-cpp-python==0.2.54` and it's working again
