### ISSUE TITLE
Issue with Glossary URL

### ISSUE THREAD

**Issue by misbullah** [rayliuca/T-Ragx#17]
Hi,

I want to try your great work. However, the running code will throw an error based on the following line:

https://l8u0.c18.e2-1.dev/t-ragx-public/glossary

It cannot be found.

How to solve the issue?

Thanks a lot

**Comment by rayliuca** [comment]
Hi @misbullah, thanks for letting me know! (Sorry that I have missed this issue)

I moved the S3 provider to Backblaze and some of the urls were not updated. It should be working now. If there's other errors, please let me know

Cheers,
