### ISSUE TITLE
Performance against NMT models 

### ISSUE THREAD

**Issue by King-Rafat** [rayliuca/T-Ragx#19]
Great work!

How does your work fair against SOTA NMT models like SeamlessM4t, NLLB, m2m?

Thank you!

**Comment by rayliuca** [comment]
Hi @King-Rafat! 

You can check out the [eval results](https://github.com/rayliuca/T-Ragx/blob/main/reports/eval_overview.md) or the [write-up](https://github.com/rayliuca/T-Ragx/blob/main/reports/README.md)

The `seamless` is referring the `SeamlessM4t` model. SeamlessM4t, being a multimodal model, is not really specialized SOTA in text-to-text translation, while NLLB and m2m focused more on the number of languages they support 

If the languages you are looking for are supported, you might want to check out models like [google/madlad400-10b-mt](https://huggingface.co/google/madlad400-10b-mt), [Unbabel/TowerInstruct-7B-v0.2](https://huggingface.co/Unbabel/TowerInstruct-7B-v0.2), etc

T-Ragx is a RAG system-based system, so it generally provides some improvement over whatever underlying model you use, especially for jargon-heavy use cases. Checkout the write-up for more details!
